stages:
  preprocess:
    cmd: python .\src\preprocess.py
    deps:
    - .\src\preprocess.py
    - .\data\raw\
    outs:
    - .\data\processed\train_data.csv

  train:
    cmd: python .\src\train.py
    deps:
      - .\src\train.py
      - .\data\processed\train_data.csv
    outs:
      - .\models\model.pkl
  test:
    cmd: python .\src\test.py
    deps:
      - .\src\test.py
      - .\data\processed\test_data.csv
      - .\models\model.pkl
    outs:
      - lifecycle.log